### ISSUE TITLE
No.1 : GitHub 기초 세션 - 과제 제출

### ISSUE THREAD

**Issue by ziweek** [kubs-bada/bada-2#1]
안녕하세요!

9월 20일에
No.1 : GitHub 기초 세션을 진행한 김지욱입니다.

여러분을 위한 과제는 다음과 같습니다.

    1. git 댓글 달기

그리고 이 과제를
다음과 같은 형식으로 제출해주시면 감사하겠습니다!

1. 이름
2. 과제가 있는 repo의 링크
3. 과제 내용이 나타난 스크린샷

-----
예시)

1. 김지욱
2. https://github.com/ziweek/bada/tree/master/sessions/session-1
3. 
<img width="895" alt="Screen Shot 2022-09-12 at 12 51 12 AM" src="https://user-images.githubusercontent.com/99459331/189536922-ee407511-0d9c-4e9a-b5bd-e73bd834e389.png">

**Comment by yongjinColinChoi** [comment]
1. 최용진
2. https://github.com/yongjinColinChoi/bada
3. 
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/84372075/191250332-c05e6b05-9bc8-4360-9882-c5edbb7359a3.png">

**Comment by sorrrrani** [comment]
1. 권소현
2. https://github.com/sorrrrani/bada-repo
3. 
![image](https://user-images.githubusercontent.com/113989383/191398450-364a9056-e7bc-4c76-b057-aabb80590977.png)

**Comment by feelief** [comment]
1. 이정수
2. https://github.com/feelief/bada
3. 
![image](https://user-images.githubusercontent.com/103921798/191430492-ff5e5830-bef8-404b-ae8a-b36f09f451d8.png)

**Comment by codhs** [comment]
1. 최혜온
2. https://github.com/codhs/bada_repo
3. 
<img width="864" alt="bada git" src="https://user-images.githubusercontent.com/113979202/191516569-7fc7e6c8-df0a-4172-ad0d-5168c8ad2555.PNG">

**Comment by sohyeon1** [comment]
1. 박소현
2. https://github.com/sohyeon1/bada
3. 
<img width="947" alt="png" src="https://user-images.githubusercontent.com/113989433/191642647-0acf4916-dbc6-47a4-b1de-17a737008313.png">

**Comment by soooonkim** [comment]
1. 김수은
2. https://github.com/soooonkim/bada2022
3. 
![image](https://user-images.githubusercontent.com/113989411/191672005-2b128eb8-7420-4de0-97b7-5bc107ff467a.png)

**Comment by itsjimin** [comment]
1. 오지민
2. https://github.com/itsjimin/bada_repo
3. 
![깃허브1](https://user-images.githubusercontent.com/108680244/191681613-6259e4e2-f432-44bb-9c7a-da87b23494b4.jpg)

**Comment by JunghyunKim9** [comment]
1. 김정현
2. https://github.com/JunghyunKim9/bada
![캡처](https://user-images.githubusercontent.com/113989454/191878523-aabb0130-ecd1-4185-a75a-9467ad163417.PNG)

**Comment by turtle98** [comment]
1.송태훈
2.https://github.com/turtle98/bada
3.
![image](https://user-images.githubusercontent.com/95213688/191905884-434632c5-e91c-490c-bd55-f6bda8bf9122.png)
